# Generated by Django 3.1 on 2020-09-13 17:36

from django.db import migrations, models
import static_content.utils


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200827_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=static_content.utils.upload_to),
        ),
        migrations.AlterField(
            model_name='poll',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
